const $=s=>document.querySelector(s); const store={get:(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)),set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
let tab='today'; let routines=store.get('routines',[{name:'Push Day',exercises:[{name:'Bench Press',sets:3,min:8,max:12,increment:2.5},{name:'Shoulder Press',sets:3,min:8,max:12,increment:2.5},{name:'Tricep Pushdown',sets:3,min:10,max:15,increment:2.5}]}]);
let history=store.get('history',[]), body=store.get('body',[]), runs=store.get('runs',[]), steps=store.get('steps',0);
const tabs=[['today','⌂','Today'],['workout','▣','Workout'],['run','▶','Run'],['progress','↗','Progress'],['body','◉','Body']];
function save(){store.set('routines',routines);store.set('history',history);store.set('body',body);store.set('runs',runs);store.set('steps',steps)}
function nav(){ $('#tabs').innerHTML=tabs.map(([id,i,n])=>`<button class="${tab===id?'active':''}" onclick="tab='${id}';render()"><span class="tabicon">${i}</span>${n}</button>`).join('') }
function render(){ const f={today,workout,run,progress,bodyView:body}; $('#app').innerHTML=(tab==='body'?bodyPage():f[tab]()); nav() }
function today(){let w=body.at(-1)?.weight||'—';return `<div class="muted">${new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</div><h1>Today</h1><div class="card"><div class="row"><div><div class="muted">STEPS</div><div class="big">${Number(steps).toLocaleString()}</div></div><span class="pill">Goal 10,000</span></div><div class="progress"><div style="width:${Math.min(100,steps/100)}%"></div></div><button class="btn secondary" onclick="editSteps()">Update steps</button></div><div class="card"><div class="muted">TODAY'S WORKOUT</div><h2 style="margin:6px 0">${routines[0]?.name||'No routine'}</h2><button class="btn" onclick="startWorkout(0)">Start Workout</button></div><div class="grid"><div class="card"><div class="metric">Body weight</div><div class="value">${w}${w==='—'?'':' kg'}</div></div><div class="card"><div class="metric">This week</div><div class="value">${history.filter(x=>Date.now()-x.date<604800000).length} workouts</div></div></div>`}
function workout(){return `<h1>Workout</h1><div class="muted">Your routines</div>${routines.map((r,i)=>`<div class="card"><div class="row"><div><div class="value">${r.name}</div><div class="muted">${r.exercises.length} exercises</div></div><button class="pill" onclick="startWorkout(${i})">Start</button></div></div>`).join('')}<button class="btn" onclick="addRoutine()">+ Create Routine</button>`}
function suggestion(name){let last=[...history].reverse().flatMap(x=>x.exercises||[]).find(e=>e.name===name);if(!last)return 0;let all=last.sets.every(s=>s.reps>=last.max);return +(last.sets[0].weight+(all?last.increment:0)).toFixed(2)}
function startWorkout(i){let r=routines[i];let html=`<h1>${r.name}</h1><div class="muted">Log each working set</div>`;r.exercises.forEach((e,ei)=>{let sug=suggestion(e.name);html+=`<div class="card exercise" data-name="${e.name}" data-min="${e.min}" data-max="${e.max}" data-inc="${e.increment}"><div class="row"><div><div class="value">${e.name}</div><div class="muted">${e.sets} × ${e.min}–${e.max} reps</div></div><span class="pill">Suggested ${sug||'—'} kg</span></div>${Array.from({length:e.sets},(_,si)=>`<div class="setrow"><b>${si+1}</b><input class="input weight" type="number" inputmode="decimal" placeholder="kg" value="${sug||''}"><input class="input reps" type="number" inputmode="numeric" placeholder="reps"><button class="check">✓</button></div>`).join('')}</div>`});html+=`<button class="btn" onclick="finishWorkout('${r.name.replaceAll("'","\\'")}')">Finish Workout</button><button class="btn secondary" onclick="render()">Cancel</button>`;$('#app').innerHTML=html;$('#tabs').innerHTML=''}
function finishWorkout(name){let ex=[...document.querySelectorAll('.exercise')].map(el=>({name:el.dataset.name,min:+el.dataset.min,max:+el.dataset.max,increment:+el.dataset.inc,sets:[...el.querySelectorAll('.setrow')].map(r=>({weight:+r.querySelector('.weight').value||0,reps:+r.querySelector('.reps').value||0}))}));history.push({name,date:Date.now(),exercises:ex});save();tab='progress';render()}
function run(){return `<h1>Run</h1><div class="muted">Manual run logging for the web version</div>${runs.slice().reverse().map(r=>`<div class="card"><div class="row"><div class="value">${r.distance} km</div><div>${r.minutes} min</div></div></div>`).join('')}<div class="card"><input id="dist" class="input" type="number" placeholder="Distance (km)"><input id="mins" class="input" type="number" placeholder="Duration (minutes)"><button class="btn" onclick="addRun()">Save Run</button></div>`}
function progress(){let total=history.reduce((a,w)=>a+w.exercises.reduce((b,e)=>b+e.sets.reduce((c,s)=>c+s.weight*s.reps,0),0),0);return `<h1>Progress</h1><div class="grid"><div class="card"><div class="metric">Workouts</div><div class="big">${history.length}</div></div><div class="card"><div class="metric">Total volume</div><div class="big">${Math.round(total).toLocaleString()}</div><div class="muted">kg</div></div></div><h2>Recent workouts</h2>${history.slice().reverse().slice(0,8).map(w=>`<div class="card"><div class="row"><b>${w.name}</b><span class="muted">${new Date(w.date).toLocaleDateString()}</span></div></div>`).join('')||'<div class="card muted">Complete a workout to start tracking progress.</div>'}`}
function bodyPage(){return `<h1>Body</h1><div class="card"><input id="bw" class="input" type="number" inputmode="decimal" placeholder="Weight (kg)"><input id="waist" class="input" type="number" inputmode="decimal" placeholder="Waist (cm)"><button class="btn" onclick="addBody()">Add Measurement</button></div><h2>History</h2>${body.slice().reverse().map(b=>`<div class="card"><div class="row"><div><div class="value">${b.weight} kg</div><div class="muted">Waist ${b.waist||'—'} cm</div></div><span class="muted">${new Date(b.date).toLocaleDateString()}</span></div></div>`).join('')||'<div class="card muted">No measurements yet.</div>'}`}
function editSteps(){let x=prompt('Steps today',steps);if(x!==null){steps=Math.max(0,+x||0);save();render()}}function addRun(){let d=+$('#dist').value,m=+$('#mins').value;if(d&&m){runs.push({distance:d,minutes:m,date:Date.now()});save();render()}}function addBody(){let w=+$('#bw').value,wa=+$('#waist').value;if(w){body.push({weight:w,waist:wa,date:Date.now()});save();render()}}function addRoutine(){let n=prompt('Routine name');let e=prompt('Exercises, separated by commas');if(n&&e){routines.push({name:n,exercises:e.split(',').map(x=>({name:x.trim(),sets:3,min:8,max:12,increment:2.5}))});save();render()}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
